version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - circleci-user

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/sources-python:0.7.0
    steps:
      - checkout
      - run:
          name: 'Setup virtualenv'
          command: |
            pyenv global 3.9.6
            mkdir -p ~/.virtualenvs
            python3 -m venv ~/.virtualenvs/target-stitch
            source ~/.virtualenvs/target-stitch/bin/activate
            pip install -U pip setuptools
            pip install -e .[dev]
            pip install -U pylint
      - run:
          name: 'Run tests'
          command: |
            # Need to re-activate the virtualenv
            source ~/.virtualenvs/target-stitch/bin/activate
            nosetests -v tests/activate_version_tests.py
            nosetests -v --ignore-files=activate_version_tests.py
            #nosetests
            pylint target_stitch "--extension-pkg-whitelist=ciso8601" --max-positional-arguments=3 -d 'global-variable-not-assigned, consider-using-generator, broad-exception-raised, unused-argument'
